-- 코드를 작성해주세요
SELECT
    i.ITEM_ID AS ITEM_ID,
    i.ITEM_NAME AS ITEM_NAME,
    i.RARITY AS RARITY
FROM
    ITEM_TREE t
JOIN
    ITEM_INFO i ON t.ITEM_ID = i.ITEM_ID
WHERE t.ITEM_ID NOT IN (SELECT PARENT_ITEM_ID FROM ITEM_TREE WHERE PARENT_ITEM_ID IS NOT NULL)
ORDER BY
    i.ITEM_ID DESC;