-- 코드를 입력하세요
SELECT
    i.FOOD_TYPE,
    i.REST_ID,
    i.REST_NAME,
    i.FAVORITES
FROM
    REST_INFO i
JOIN
    (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES FROM REST_INFO
        GROUP BY FOOD_TYPE
    ) f ON i.FOOD_TYPE = f.FOOD_TYPE
WHERE
    i.FAVORITES = f.FAVORITES
ORDER BY
    i.FOOD_TYPE DESC;

    