-- 코드를 입력하세요


SELECT
    YEAR(s.SALES_DATE) AS YEAR,
    MONTH(s.SALES_DATE) AS MONTH,
    u.GENDER AS GENDER,
    COUNT(DISTINCT s.USER_ID) AS USERS
FROM
    ONLINE_SALE s
JOIN 
    (SELECT * FROM USER_INFO WHERE GENDER IS NOT NULL) AS u
        ON s.USER_ID = u.USER_ID
GROUP BY
    YEAR, MONTH, GENDER
ORDER BY
    YEAR, MONTH, u.GENDER;