-- 코드를 작성해주세요
SELECT
   COUNT(id) AS FISH_COUNT,
   MAX(length) AS MAX_LENGTH,
   FISH_TYPE
FROM
    FISH_INFO
GROUP BY
    FISH_TYPE
HAVING
    AVG(COALESCE(LENGTH, 10)) >= 33
ORDER BY
    FISH_TYPE;